# Generated by Django 4.2.13 on 2024-05-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_subtask_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('L', 'Не важные'), ('H', 'Важные'), ('M', 'Средние')], default='L', max_length=1),
        ),
    ]
