# Generated by Django 4.2.13 on 2024-06-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_days_left_alter_task_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('M', 'Средне'), ('L', 'Не важно'), ('H', 'Важно')], default='L', max_length=1),
        ),
    ]
